main: main.o controller.o sigCluster.o
	g++ -lomp -O3 main.o controller.o sigCluster.o  -lm -lgsl -lgslcblas -lboost_iostreams -lz  -o fastenloc
main.o: main.cc
	g++ -c  main.cc
controller.o: controller.cc controller.h
	g++ -Xpreprocessor -fopenmp   -c  controller.cc
sigCluster.o: sigCluster.h sigCluster.cc
	g++ -c sigCluster.cc 
clean:
	rm *.o fastenloc
